### ISSUE TITLE
Side effects in toggleVisibilityOfCells

### ISSUE THREAD

**Issue by bartleby** [k06a/ABIntentions#1]
Привет, в классе `ABTableViewDelegateHideRowsIntention.m`
метод `- (IBAction)toggleVisibilityOfCells:(id)sender`

Имеется сайд эффект, toggleVisibilityOfCells как правило линкуется на свич, и если переключить свич и не отпускать палец (как бы подвинуть палец, переключая свич а не просто тап) и двигать по экрану, то:
1. начинает прыгать то что скрываем
2. теряется позиция ON/OFF т.е после того как отпустим палец, может быть инверт значений.
из-за `self.isCellsHidden = !self.isCellsHidden;`

Поправить можно привязав toggleVisibilityOfCells к UISwitch 
я написал простую категорию

```
#import "ABTableViewDelegateHideRowsIntention.h"

@interface ABTableViewDelegateHideRowsIntention (Switch)

- (IBAction)switchVisibilityOfCells:(UISwitch *)sender;

@end

```

```
#import "ABTableViewDelegateHideRowsIntention+Switch.h"

@implementation ABTableViewDelegateHideRowsIntention (Switch)

- (IBAction)switchVisibilityOfCells:(UISwitch *)sender
{
    if (self.isCellsHidden == !sender.isOn) return;
    [self toggleVisibilityOfCells:sender];
}

@end
```

**Comment by bartleby** [comment]
И сразу тут спрошу, как скрыть ячейки без анимации? например при старте нужно сформировать по модельке состояния таблички, я добился только костыльного способа, но он  работает, может быть есть более нормальный?

**Comment by k06a** [comment]
Без анимации я делаю вот этой штукой: `[UIView performWithoutAnimation:]`

**Comment by bartleby** [comment]
Спасибо! =)

**Comment by k06a** [comment]
По поводу первого сообщения, получается перегрузка такая? Странно, я был уверен, что в Obj-C нет перегрузки методов :)

**Comment by bartleby** [comment]
Это обычная категория, можно расширять любой класс, я расширил твою либу и добавил свой метод со своей логикой, можно так же поступить с любым другим классом например с NSString  [string md5] будет отдавать новую строку в мд5, очень частое явление в objc, но таким макаром нельзя добавить свойство, точнее можно, но с помощью рантайма =)

**Comment by k06a** [comment]
Что такое категория понятно. Я задумался о том, что в категории переопределен тот же метод для конкретного типа аргумента. Как специализация шаблона в C++.

**Comment by k06a** [comment]
Если не сложно попрошу форкнуть, добавить `@interface` и `@implementation` категорий в те же файлы, где и оригиналы лежат, коммитнуть к себе и нажать PullRequest. Тогда это улучшение будет официально Вами законтрибьючено. Надо только проверить что в случае с не-UISwitch будет вызываться старый метод.

**Comment by k06a** [comment]
А я просто подумал что у методов одинаковые имена - разные типы параметров `id` и `UISwitch*` - вот и удивился про при вызове срабатывает перегрузка :))

**Comment by k06a** [comment]
Чуть упростил, убрал динамическое свойство.

**Comment by bartleby** [comment]
да, точно, оно лишнее =)
